# Generated by Django 5.1 on 2024-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
