# Generated by Django 5.1 on 2024-09-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-fecha'], 'permissions': [('can_edit_order', 'can edit order')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
